AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Instance with IAM Role to Backup Logs to S3

Resources:

  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-backup-${AWS::AccountId}-${AWS::Region}"
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveAndExpire
            Status: Enabled
            Prefix: "backups/"
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 30
            ExpirationInDays: 90

  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BackupS3Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3UploadPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub "arn:aws:s3:::s3-backup-${AWS::AccountId}-${AWS::Region}/backups/*"

  BackupInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BackupRole

  BackupInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (update if needed)
      IamInstanceProfile: !Ref BackupInstanceProfile
      KeyName: your-key-pair  # Replace with your actual key name
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y python3 zip aws-cli
          pip3 install boto3
          echo "*/30 * * * * /usr/bin/python3 /home/ec2-user/backup-to-s3.py" >> /var/spool/cron/ec2-user
